FROM ruby:3.4.5-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the repository
COPY . .

# Install development dependencies
RUN bin/rake setup

CMD ["/bin/bash"]
