source "https://rubygems.org"

ruby ">= 3.1"

gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"
gem "rack", "~> 3.0"
gem "puma", "~> 6.0"
gem "sequel", "~> 5.0"
gem "sqlite3", "~> 2.0"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.7"

group :development, :test do
  gem "rack-test", "~> 2.0"
  gem "rspec", "~> 3.12"
  gem "webmock", "~> 3.23"
end
